History: Prepare .site to generate

diff --git a/.github/workflows/ci-flow.yml b/.github/workflows/ci-flow.yml
--- a/.github/workflows/ci-flow.yml
+++ b/.github/workflows/ci-flow.yml
@@ -132,9 +132,10 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Configure github pages
+        id: gh-pages
         uses: actions/configure-pages@v5
 
-      - name: Checkout repositorybuild_site
+      - name: Checkout project repository
         uses: actions/checkout@v4
 
       - name: Checkout github-pages repository
@@ -142,7 +143,7 @@ jobs:
         with:
           repository: shikofx/github-pages
           path: gh-pages-repo
-          token: ${{ secrets.GH_PAGES_PAT }} # Используем PAT для доступа
+          token: ${{ secrets.GH_PAGES_PAT }} 
 
       - name: Download artifacts
         uses: actions/download-artifact@v4
@@ -151,18 +152,15 @@ jobs:
 
       - name: Prepare .site content
         run: |
-          mkdir -p .site/reports/swiftlint
-          mv .artifacts/swiftlint-report/* .site/reports/swiftlint/ || echo "swiftlint-report not found"
+          mkdir -p .site/reports/swiftlint && mv .artifacts/swiftlint-report/* .site/reports/swiftlint/ || echo "swiftlint-report not found"
           mkdir -p .site/reports/swiftformat && mv .artifacts/swiftformat-report/* .site/reports/swiftformat/ || echo "swiftformat-report not found"
-          mkdir -p .site/reports/coverage
-          mv .artifacts/coverage-report/* .site/reports/coverage/ || echo "coverage-report directory not found"
-          mkdir -p .site/reports/allure
-          mv .artifacts/allure-report/* .site/reports/allure/ || echo "allure-report not found"
+          mkdir -p .site/reports/coverage && mv .artifacts/coverage-report/* .site/reports/coverage/ || echo "coverage-report not found"
+          mkdir -p .site/reports/allure && mv .artifacts/allure-report/* .site/reports/allure/ || echo "allure-report not found"
           mv .artifacts/index-page-with-allure/index.md .site/index.md || echo "index.md not found"
-          cat .artifacts/index-page-with-allure/_config.yml >> .site/_config.yml || echo "_config.yml not found"
 
       - name: Inject GitHub metadata into Jekyll config
         run: |
+          cat .artifacts/index-page-with-allure/_config.yml >> .site/_config.yml || echo "_config.yml not found"
           echo "Adding GitHub metadata to .site/_config.yml"
           echo "" >> .site/_config.yml
           echo "timezone: Europe/Minsk" >> .site/_config.yml
